# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-09-14 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipos', '0002_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipo_pago',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
