# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla_visado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilladevisado',
            name='elementos',
            field=models.ManyToManyField(related_name='elementos_balance', to='planilla_visado.Elemento_Balance_Superficie'),
        ),
    ]
