# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-26 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla_visado', '0002_planilladevisado_elementos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionesVisado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
    ]
