# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-27 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla_visado', '0003_observacionesvisado'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilladevisado',
            name='observaciones',
            field=models.ManyToManyField(related_name='observaciones_visado', to='planilla_visado.ObservacionesVisado'),
        ),
    ]
