# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-29 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planilla_visado', '0004_planilladevisado_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planilladevisado',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='planilladevisado',
            name='observacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observacion_visado', to='planilla_visado.ObservacionesVisado'),
        ),
    ]
