# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-01-04 22:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilla_visado', '0007_auto_20191222_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planilladevisado',
            name='observaciones',
        ),
        migrations.DeleteModel(
            name='ObservacionesVisado',
        ),
    ]
