# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-01-05 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planilla_visado', '0008_auto_20200104_2253'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionesVisado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='planilladevisado',
            name='observacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observacion', to='planilla_visado.ObservacionesVisado'),
        ),
    ]
