# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-01-05 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla_visado', '0009_auto_20200105_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planilladevisado',
            name='observacion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='ObservacionesVisado',
        ),
    ]
