# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-09-14 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla_visado', '0010_auto_20200105_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='columnadevisado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='elemento_balance_superficie',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='filadevisado',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='itemdevisado',
            name='enUso',
            field=models.BooleanField(default=True),
        ),
    ]
