# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 22:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tramite', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaInspeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=300)),
                ('tipo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleDeItemInspeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('categoria_inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='planilla_inspeccion.CategoriaInspeccion')),
            ],
            options={
                'ordering': ['item_inspeccion', 'categoria_inspeccion'],
            },
        ),
        migrations.CreateModel(
            name='ItemInspeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlanillaDeInspeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalles', models.ManyToManyField(related_name='planillasInspeccion', to='planilla_inspeccion.DetalleDeItemInspeccion')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='tramite.Tramite')),
            ],
        ),
        migrations.AddField(
            model_name='detalledeiteminspeccion',
            name='item_inspeccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='planilla_inspeccion.ItemInspeccion'),
        ),
    ]
