# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-11-29 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilla_inspeccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planilladeinspeccion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
