# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 20:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planilla_visado', '0003_auto_20171114_2059'),
        ('planilla_inspeccion', '0002_remove_iteminspeccion_categorias'),
        ('tramite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='planillaInspeccion',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planilla_inspeccion.PlanillaDeInspeccion'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='planillaVisado',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planilla_visado.PlanillaDeVisado'),
        ),
    ]
