# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-03-14 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0002_auto_20171122_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendado',
            name='rol',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Iniciado'), (2, 'Aceptado'), (3, 'Visado'), (4, 'Corregido'), (5, 'Agendado'), (6, 'Con Inspeccion'), (7, 'Inspeccionado'), (8, 'Final de obra solicitado'), (9, 'Finalizado'), (1, b'iniciado'), (2, b'aceptado'), (3, b'visado'), (4, b'corregido'), (5, b'agendado'), (7, b'inspeccionado'), (9, b'finalizado'), (6, b'coninspeccion'), (8, b'finalobrasolicitado')]),
        ),
    ]
