# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 20:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0002_auto_20171024_2119'),
        ('tramite', '0002_auto_20171114_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='tramite',
        ),
        migrations.AddField(
            model_name='tramite',
            name='pago',
            field=models.ForeignKey(blank=True, default=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pago.Pago'),
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
    ]
