# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-03-17 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0003_auto_20191222_2342'),
        ('tramite', '0003_auto_20200314_1554'),
    ]

    operations = [
    ]
