# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-08-06 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0004_merge_20200317_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='circunscripcion',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='domicilio',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='manzana',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='parcela',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='sector',
            field=models.IntegerField(),
        ),
    ]
