# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2020-12-03 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0005_auto_20200806_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='mactivo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
