# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaVencimiento', models.DateField(blank=True, null=True)),
                ('fechaPago', models.DateField()),
                ('monto', models.IntegerField(blank=True, null=True)),
                ('numeroCuota', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.PositiveSmallIntegerField(choices=[(0, 'Estado'), (1, b'cancelacion'), (2, b'cancelada')])),
                ('marca', models.DateTimeField(auto_now=True)),
            ],
            options={
                'get_latest_by': 'timestamp',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('cantidadCuotas', models.IntegerField(blank=True, choices=[(1, 'Una Cuota'), (3, 'Tres Cuotas'), (6, 'Seis Cuotas'), (12, 'Doce Cuotas')], null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pago.Cuota')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPago', models.CharField(choices=[('A', 'Debito'), ('B', 'Efectivo')], max_length=2)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cancelacion',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pago.Estado')),
            ],
            bases=('pago.estado',),
        ),
        migrations.CreateModel(
            name='Cancelada',
            fields=[
                ('estado_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pago.Estado')),
            ],
            bases=('pago.estado',),
        ),
        migrations.AddField(
            model_name='pago',
            name='tipoPago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pago.Tipo_Pago'),
        ),
        migrations.AddField(
            model_name='estado',
            name='cuota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estados_cuota', to='pago.Cuota'),
        ),
    ]
