# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-17 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='fechaPago',
            field=models.DateField(null=True),
        ),
    ]
