# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-21 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0002_auto_20171117_1657'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'get_latest_by': 'marca'},
        ),
        migrations.RemoveField(
            model_name='pago',
            name='cuota',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='valor',
        ),
        migrations.AddField(
            model_name='cuota',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='pago.Pago'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='fechaPago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estado',
            name='cuota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estado_cuota', to='pago.Cuota'),
        ),
    ]
