# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pago', '0003_auto_20171121_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
